[package]
name = "breezy1214/hitbox"
description = "A flexible, efficient hitbox system for Roblox games that supports both server and client-side hit detection."
version = "5.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Janitor = "howmanysmall/janitor@1.18.3"
